sonar.projectKey=sqp_ba49e65173aeb66281da6ea9a0d8db296b59d466
sonar.projectName=TFG
sonar.sources=src
sonar.exclusions=Prueba/**, .claude/**, .vscode/**, entorno/**, **/*.csv, **/*.pdf, **/*.ipynb, **/*.keras, **/*.db, **/*.md