sonar.projectKey=TFG
sonar.projectName=TFG
sonar.sources=src/hives
sonar.tests=tests
sonar.exclusions=Prueba/**, dist/**, .vscode/**, entorno/**, **/*.csv, **/*.pdf, **/*.ipynb, **/*.keras, **/*.db, **/*.md, **/site-packages/**, **/__pycache__/**,.venv/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.token=${sonarQube_token}
sonar.host.url=http://192.168.0.43:9000
